- hosts: katello-remote-db
  remote_user: root
  any_errors_fatal: true
  roles:
    - setup
    - { role: backup,
        backup_name: offline,
        backup_type: offline,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz"],
        hammer_check: true

      }
    - { role: backup,
        backup_name: online,
        backup_type: online,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz"],
        hammer_check: true

      }
    - { role: backup,
        backup_name: standard_without_pulp_content,
        backup_type: offline,
        backup_args: --skip-pulp-content,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz", "pulp_data.tar"],
        hammer_check: true

      }
    - { role: backup,
        backup_name: online_without_pulp_content,
        backup_type: online,
        backup_args: --skip-pulp-content,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz", "pulp_data.tar"],
        hammer_check: true
      }
    - { role: backup,
        backup_name: logical,
        backup_type: offline,
        backup_args: --include-db-dumps,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz"],
        hammer_check: true
      }
