- hosts: katello
  remote_user: root
  roles:
   - setup
   - { role: backup,
        backup_name: online,
        backup_type: online,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz"],
        hammer_check: true
      }

