- hosts: katello
  remote_user: root
  roles:
    - setup
    - { role: backup,
        backup_type: standard,
        good_files:  ["config_files.tar.gz", "mongo_data.tar.gz", "pgsql_data.tar.gz", "pulp_data.tar"],
        bad_files: ["foreman.dump", "candlepin.dump", "mongo_dump"]
      }
    - { role: backup,
        backup_type: online,
        backup_args: --online,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz"]
      }
    - { role: backup,
        backup_type: standard-without-pulp-content,
        backup_args: --skip-pulp-content,
        good_files:  ["config_files.tar.gz", "mongo_data.tar.gz", "pgsql_data.tar.gz"],
        bad_files: ["foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"]
      }
    - { role: backup,
        backup_type: online-without-pulp-content,
        backup_args: --online --skip-pulp-content,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump"],
        bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz", "pulp_data.tar"]
      }
    - { role: backup,
        backup_type: logical,
        backup_args: --logical-db-backup,
        good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "mongo_data.tar.gz", "pgsql_data.tar.gz", "pulp_data.tar"],
        bad_files: []
      }
