- name: "create unique backup directory"
  file: 
    path: "/backup/{{ backup_type }}{{ ansible_date_time.epoch }}"
    state: directory

- name: run katello-backup
  command: "/katello-packaging/katello/katello-backup -y {{ backup_args }} --preserve-dir /backup/{{ backup_type }}{{ ansible_date_time.epoch }}"
  register: backup_output
  become: root

- name: check {{ backup_type }} backup files
  backup_files_exist:
    good_files: "{{ good_files }}"
    bad_files: "{{ bad_files }}"
    directory: "/backup/{{ backup_type }}{{ ansible_date_time.epoch }}"

- name: run {{ backup_type }} katello-restore
  command: "/katello-packaging/katello/katello-restore -y -d  /backup/{{ backup_type }}{{ ansible_date_time.epoch }}"
  become: root
  when: run_restore

- name: "remove {{ backup_type }} directory"
  file:
    path: "/backup/{{ backup_type }}{{ ansible_date_time.epoch }}"
    state: absent
  when: clean_up_backup_dir
