- name: "remove {{ backup_type }} backup output file"
  file: 
    path: /tmp/standard-backup.txt
    state: absent

- name: run katello-backup
  command: "/katello-packaging/katello/katello-backup {{ backup_args }} /backup"
  register: backup_output
  become: root

- name: copy backup output to file
  copy: 
    content: "{{ backup_output.stdout }}"
    dest: "/tmp/{{ backup_type }}-backup.txt"

- name: "get {{ backup_type }} backup directory"
  shell: "sed -n 2p /tmp/{{ backup_type }}-backup.txt | awk '{print $4}'"
  register: backup_dir

- name: check standard backup files
  backup_files_exist:
    good_files: "{{ good_files }}"
    bad_files: "{{ bad_files }}"
    directory: "{{ backup_dir.stdout }}"

- name: run katello-restore
  command: "yes | /katello-packaging/katello/katello-restore {{ backup_args }} {{ backup_dir.stdout }}"
  register: backup_output
  become: root
