hammer_check: true
scenario_names: ["online", "offline", "offline_no_pulp", "online_no_pulp", "offline_include_dumps"]
scenarios:
  offline:
    backup_type: offline
    backup_args: ""
    good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"]
    bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz"]
  online:
    backup_type: online
    backup_args: ""
    good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"]
    bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz"]
  offline_no_pulp:
    backup_type: offline
    backup_args: --skip-pulp-content
    good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump"]
    bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz", "pulp_data.tar"]
  online_no_pulp:
    backup_type: online
    backup_args: --skip-pulp-content
    good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump"]
    bad_files: ["mongo_data.tar.gz", "pgsql_data.tar.gz", "pulp_data.tar"]
  offline_include_dumps:
    backup_type: offline
    backup_args: --include-db-dumps
    good_files: ["config_files.tar.gz", "foreman.dump", "candlepin.dump", "mongo_dump", "pulp_data.tar"]
    bad_files: []
